[cisco]
cisco_switch1 ansible_host=172.20.10.10
cisco_switch2 ansible_host=172.20.10.11
cisco_switch3 ansible_host=172.20.10.12
cisco_switch4 ansible_host=172.20.10.13

[qtech]
qtech ansible_host=192.168.0.30
