#SPDX-License-Identifier: MIT-0
---
# tasks file for first_role

- name: install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes